Feature/test shell
DanielPlontia/SSD_Shell pull request #12
Opened 2024-06-04 07:33 UTC by duddud017

testShell의 full read function을 구현하였습니다.
실제로 file read 하는 부분은 현재 없어, Mock function 으로 생성하여 test code 를 작성하였습니다.
실제 result.txt 파일이 생기면 해당 부분이 연결이 될 예정 입니다.

2024-06-04 07:39 UTC, kimtaekun requested changes
comment 확인 부탁드립니다!

2024-06-04 07:39 UTC, kimtaekun commented on SSD/TestShell/TestShell.cpp
> +    sddExeRunner ssdExe;
sdd 오타인걸까요??

```suggestion
    ssdExeRunner ssdExe;
```

2024-06-04 07:45 UTC, duddud017 commented on SSD/TestShell/TestShell.cpp
> +    sddExeRunner ssdExe;
오타 맞습니다^^ 확인 감사합니다. sdd->ssd 로 변경하며 Runner 보다는 조금 더 직관적인 executor 로 class 명 변경하였습니다.

2024-06-04 07:59 UTC, heeju00627 requested changes
result.txt가 commit에 올라오지 않아도 좋을 것 같아요~

2024-06-04 23:37 UTC, duddud017 commented
> result.txt가 commit에 올라오지 않아도 좋을 것 같아요~

파일 삭제했습니다~^^ 감사합니다.

2024-06-04 23:44 UTC, DanielPlontia commented
FullRead관련 구현이 잘 되었습니다.

2024-06-04 23:44 UTC, DanielPlontia approved these changes

2024-06-04 23:53 UTC, kimtaekun approved these changes
Full Read 기능이 잘 구현된 거 같습니다!

2024-06-05 00:00 UTC, 20092498 approved these changes
받아서 코드 확인하도록하겠습니다.

2024-06-05 00:06 UTC, heeju00627 approved these changes

2024-06-05 00:06 UTC, merged