SSD Invoker 개발 완료 및 Test 코드 추가
DanielPlontia/SSD_Shell pull request #16
Opened 2024-06-04 23:50 UTC by 20092498

read, write, ssd_hw 와 모두 연계된 부분으로 개발이 늦었습니다.
확인 부탁드립니다.

2024-06-04 23:59 UTC, DanielPlontia approved these changes
Invoker가 연관관계도 많고 가장 복잡했던 것 같습니다.
수고하셨습니다.

2024-06-05 00:00 UTC, kimtaekun approved these changes
잘 구현된거 같습니다
고생하셨습니다!
Invoker는 내부 Instance를 전부 Managing해야 하는 case라
test를 어떻게 구현하면 좋을지 한번 고민해보면 좋을거 같습니다.
고생하셨습니다!

2024-06-05 00:00 UTC, t-kun98 commented on SSD/SSD/SSD_Invoker.cpp
> +#include<iostream>
<> include 와
"" include 들을 한곳에 모아주시면 더 좋을거 같습니다!

2024-06-05 00:01 UTC, duddud017 commented on SSD/SSD/SSD_Invoker.cpp
> +
고생 많이하셨습니다~. Header 파일 의 선언 순서를 아래와 같이 변경해 보시는건 어떨까요? 조금 더 깔끔해 보일 것 같습니다. 검토 부탁드립니다.

#include<vector>
#include<string>
#include<algorithm>
#include <cctype>
#include<iostream>
#include "Command.h"
#include "SSD_HW.h"
#include "MySSD.cpp"
#include "read.cpp"
#include "write.cpp"

2024-06-05 00:04 UTC, heeju00627 requested changes

2024-06-05 00:04 UTC, heeju00627 commented on SSD/Sample-Test1/nand.txt
이 파일은 commit에 빠져도 될 것 같습니다~

2024-06-05 00:04 UTC, heeju00627 commented on SSD/SSD/SSD_Invoker.cpp
> +	string run()
mapping_instance는 test 용도에 가까운지요? main에서 invoker.run()을 호출할 땐 따로 return 값을 사용하지는 않는 것 같아서요~
문제 있는 상황에서 custom exception을 throw하고 main에서 catch후 INVALID COMMAND를 띄울 수 있도록 main 담당하시는 분과 sync 맞춰서 업데이트하면 좋을 것 같습니다~

2024-06-05 00:04 UTC, heeju00627 commented on SSD/SSD/SSD_Invoker.cpp
> +private:
가독성 위해 private과 public의 위치가 바뀌는 게 어떨지요?

2024-06-05 00:05 UTC, 20092498 commented on SSD/SSD/SSD_Invoker.cpp
> +
반영 하였습니다.

2024-06-05 00:05 UTC, 20092498 commented on SSD/SSD/SSD_Invoker.cpp
> +#include<iostream>
반영 완료하였습니다.

2024-06-05 00:06 UTC, 20092498 commented on SSD/SSD/SSD_Invoker.cpp
> +	string run()
네 해당 부분은 behavior 테스트를 위해서 들어가있는 상황입니다. factory pattern 사용시 mock 사용법에 대한 문의를 하였는데, 이부분 해결 방법이 있으면 적용하고, 딱히 없다고하면... 관련하여 협의가 필요할것같습니다.

2024-06-05 00:07 UTC, 20092498 commented on SSD/SSD/SSD_Invoker.cpp
> +private:
반영완료하였습니다.

2024-06-05 00:10 UTC, duddud017 approved these changes
잘 구현 하셨습니다. ^^ 수고 많으셨습니다~

2024-06-05 00:13 UTC, 20092498 commented on SSD/Sample-Test1/nand.txt
반영완료하였습니다.

2024-06-05 00:14 UTC, heeju00627 approved these changes
고생하셨습니다~

2024-06-05 00:14 UTC, merged